---
layout: cv
title: Zack Williams' CV
---
# Zack Williams
Student, Computer Scientist.

<div id="Linded-in">
<a href="www.linkedin.com/in/zachary-robert-williams">Click Here</a>
</div>

## Education

`2021 - Present`
__Brigham Young Unversity Idaho.__

`2014 - 2018`
__Trinity College, Cambridge__

## Employment History

`May 2024 - Present`
__AI Contractor__, Outlier.ai (Online)

- Task assignments
- Ai improvements

`November 2022 - December 2022`
__Student Consultant, Small Business Management__, BYU_I (Rexburg, Idaho)

Member of student team that consulted with Tacos El Guey, a small taco truck business operating out of Twin Falls. Owner needed an idea of when she could step away from her business.
- Created a Pro Forma based on past financial information that can be adjusted to give the owner an idea of what is needed financially for her to step away.
- Preformed an analysis on future labor cost they will endure.
- Made applicable recommendations pertaining to her current operations


`January 2021 - April 2021`
__Warehouse Associate__, PetWish (Buford, Georgia)

- Packed and labeled merchandise to prepare for loading and shipment to customers.
- Picked and prepared numerous daily shipments in controlled atmosphere warehouse environment.
- Moved boxes, containers and pallets with special-purpose equipment to meet demanding production targets.
- Organized warehouse design to maximize space for stock while allowing for high volume traffic zones.

`Febuary 2018 - December 2018`
__Warehouse Associate__, Lowe's Home Improvment (Suwanee, Georgia)

- Built and maintained relationships with peers and upper management to drive team success.
- Assisted teammates with sales-processing tasks to meet daily sales goals.

<!-- ### Footer

Last updated: September 2024 -->